"""Convert a playbook to a standalone Python runbook script."""

from __future__ import annotations

import keyword
import re
import textwrap
from typing import Any


def _indent(text: str, level: int = 1) -> str:
    """Indent text by the given number of 4-space levels."""
    return textwrap.indent(text, "    " * level)


def _safe_docstring(text: str) -> str:
    """Escape text for safe inclusion in a triple-quoted docstring."""
    return text.replace("\\", "\\\\").replace('"""', r"\"\"\"")


def _safe_str_literal(text: str) -> str:
    """Escape text for safe inclusion in a double-quoted string literal."""
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _safe_triple_str(text: str) -> str:
    """Escape text for safe inclusion in a triple-double-quoted string."""
    return text.replace("\\", "\\\\").replace('"""', r"\"\"\"')")


def _generate_variable_extraction(variables: list[dict[str, str]]) -> str:
    """Generate code to extract variables from a GuardDuty finding JSON."""
    lines = []
    for var in variables:
        var_name = var["name"]
        if keyword.iskeyword(var_name) or keyword.issoftkeyword(var_name):
            var_name = f"{var_name}_var"
        parts = var["source"].split(".")
        access = "finding"
        accessors = []
        for part in parts:
            if part == "finding":
                continue
            if "[" in part:
                name, idx = part.rstrip("]").split("[")
                accessors.append(f'.get("{name}", [])')
                accessors.append(f"[{idx}]")
            else:
                accessors.append(f'.get("{part}", {{}})')
        if accessors:
            access_chain = "finding" + "".join(accessors[:-1])
            last = accessors[-1]
            if last.startswith(".get("):
                key_match = last.split('"')[1]
                access = f'{access_chain}.get("{key_match}", "UNKNOWN")'
            else:
                access = f"{access_chain}{last}"
        lines.append(f"    {var_name} = {access}")
    return "\n".join(lines)


def _sanitize_func_name(action_id: str) -> str:
    """Convert an action ID to a valid Python function name."""
    name = re.sub(r"[^a-zA-Z0-9_]", "_", action_id).lower()
    if keyword.iskeyword(name) or keyword.issoftkeyword(name):
        name = f"{name}_action"
    if not name[0:1].isalpha() and name[0:1] != "_":
        name = f"action_{name}"
    return name


def _safe_var_names(variables: list[dict[str, str]]) -> list[str]:
    """Get safe variable names, avoiding Python keywords."""
    names = []
    for v in variables:
        name = v["name"]
        if keyword.iskeyword(name) or keyword.issoftkeyword(name):
            name = f"{name}_var"
        names.append(name)
    return names


def convert(playbook: dict[str, Any]) -> str:
    """Convert a playbook dict to a standalone Python runbook script string."""
    playbook_id = _safe_str_literal(playbook["id"])
    description = _safe_docstring(playbook.get("description", ""))
    finding_type = _safe_str_literal(playbook.get("finding_type", ""))
    variables = playbook.get("variables", [])
    var_names = _safe_var_names(variables)

    sections: list[str] = []

    # Header
    sections.append(f'''#!/usr/bin/env python3
"""
GuardDuty Playbook Runbook: {playbook_id}

{description}

Generated by guardduty-playbook-commons (gdpc).
"""

import argparse
import json
import shlex
import subprocess
import sys

try:
    import boto3
except ImportError:
    boto3 = None
''')

    # Variable extraction function
    var_extraction = _generate_variable_extraction(variables)
    sections.append(f'''
def extract_variables(finding: dict) -> dict:
    """Extract playbook variables from a GuardDuty finding."""
{var_extraction}
    return {{{", ".join(f'"{v}": {v}' for v in var_names)}}}


def _safe_format(template: str, variables: dict) -> str:
    """Format a template string with shell-escaped variables."""
    safe_vars = {{k: shlex.quote(str(v)) for k, v in variables.items()}}
    return template.format(**safe_vars)
''')

    # Triage functions
    for i, step in enumerate(playbook.get("triage", []), 1):
        step_desc = _safe_docstring(step["step"])
        step_how = _safe_triple_str(step["how"])
        sections.append(f'''
def triage_step_{i}(variables: dict, dry_run: bool = False) -> None:
    """{step_desc}"""
    print("\\n[TRIAGE STEP {i}] {step_desc}")
    cmd = _safe_format("""{step_how}""", variables)
    print(f"  How: {{cmd}}")
    if not dry_run:
        input("  Press Enter to continue...")
''')

    # Investigation functions
    investigation = playbook.get("investigation", {})
    for i, query in enumerate(investigation.get("queries", []), 1):
        query_name = _safe_docstring(query["name"])
        query_type = _safe_str_literal(query["type"])
        template_escaped = _safe_triple_str(query["template"])
        # Escape braces for f-string, then re-enable variable placeholders
        template_for_format = template_escaped.replace("{", "{{").replace("}", "}}")
        for v in var_names:
            template_for_format = template_for_format.replace(f"{{{{{v}}}}}", f"{{{v}}}")
        sections.append(f'''
def investigation_query_{i}(variables: dict, dry_run: bool = False) -> None:
    """{query_name}"""
    print("\\n[INVESTIGATION] {query_name} (type: {query_type})")
    query_text = """{template_for_format}""".format(**variables)
    print(f"  Query:\\n{{query_text}}")
''')

    # Containment functions
    containment = playbook.get("containment", {})
    automated = containment.get("automated", False)
    for action in containment.get("actions", []):
        func_name = _sanitize_func_name(action["id"])
        is_manual = not automated or action.get("requires_confirmation", False)
        action_desc = _safe_docstring(action["description"])
        action_desc_str = _safe_str_literal(action["description"])

        cli_template = _safe_triple_str(action["aws_cli"])

        if is_manual:
            sections.append(f'''
def {func_name}(variables: dict, dry_run: bool = False) -> None:
    """{action_desc}"""
    print("\\n[CONTAINMENT] {action_desc_str}")
    cmd = _safe_format("""{cli_template}""", variables)
    print(f"  Command: {{cmd}}")
    if dry_run:
        print("  [DRY RUN] Skipping execution.")
        return
    confirm = input("  Execute this action? (yes/no): ")
    if confirm.lower() == "yes":
        print("  Executing...")
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
        print(f"  Exit code: {{result.returncode}}")
        if result.stdout:
            print(f"  Output: {{result.stdout}}")
        if result.stderr:
            print(f"  Stderr: {{result.stderr}}")
    else:
        print("  Skipped.")
''')
        else:
            sections.append(f'''
def {func_name}(variables: dict, dry_run: bool = False) -> None:
    """{action_desc}"""
    print("\\n[CONTAINMENT - AUTO] {action_desc_str}")
    cmd = _safe_format("""{cli_template}""", variables)
    if dry_run:
        print(f"  [DRY RUN] Would execute: {{cmd}}")
        return
    print(f"  Executing: {{cmd}}")
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    print(f"  Exit code: {{result.returncode}}")
    if result.stdout:
        print(f"  Output: {{result.stdout}}")
    if result.stderr:
        print(f"  Stderr: {{result.stderr}}")
''')

    # Main function
    triage_calls = "\n".join(
        f"    triage_step_{i}(variables, dry_run=args.dry_run)"
        for i in range(1, len(playbook.get("triage", [])) + 1)
    )
    investigation_calls = "\n".join(
        f"    investigation_query_{i}(variables, dry_run=args.dry_run)"
        for i in range(1, len(investigation.get("queries", [])) + 1)
    )
    containment_calls = "\n".join(
        f"    {_sanitize_func_name(a['id'])}(variables, dry_run=args.dry_run)"
        for a in containment.get("actions", [])
    )

    desc_for_argparse = _safe_str_literal(playbook.get("description", ""))

    sections.append(f'''
def main() -> None:
    parser = argparse.ArgumentParser(
        description="{desc_for_argparse}"
    )
    parser.add_argument(
        "--finding-json",
        required=True,
        help="Path to a GuardDuty finding JSON file",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print all actions without executing",
    )
    args = parser.parse_args()

    with open(args.finding_json) as f:
        finding = json.load(f)

    variables = extract_variables(finding)
    print("Playbook: {playbook_id}")
    print("Finding type: {finding_type}")
    print(f"Variables: {{json.dumps(variables, indent=2)}}")

    if args.dry_run:
        print("\\n*** DRY RUN MODE — no actions will be executed ***")

    # Triage
    print("\\n" + "=" * 60)
    print("TRIAGE")
    print("=" * 60)
{triage_calls}

    # Investigation
    print("\\n" + "=" * 60)
    print("INVESTIGATION")
    print("=" * 60)
{investigation_calls}

    # Containment
    print("\\n" + "=" * 60)
    print("CONTAINMENT")
    print("=" * 60)
{containment_calls}

    print("\\nPlaybook complete.")


if __name__ == "__main__":
    main()
''')

    return "\n".join(sections)
